import db from "db"
import { Ctx } from "blitz"

export default async function getRecent(input, ctx: Ctx) {
  ctx.session.$authorize()
  //get the pdfs generated by the current user
  const pdfs = await db.pDF.findMany(input)
  // console.log(pdfs)
  const pdfmap = pdfs.map((pdf) => pdf.templateId)
  const removeNull = pdfmap.filter((pdf) => pdf !== null) as string[]
  //now get the templates that were used to generate the pdfs
  const templates = await db.template.findMany({
    where: {
      id: {
        in: removeNull,
      },
      visibility: {
        in: ["ALL", ctx.session.role],
      },
    },
    // Get the last 3 templates
    orderBy: {
      createdAt: "desc",
    },
    take: 3,
    select: {
      id: true,
      name: true,
      description: true,
    },
  })
  return templates
}
